# Ruff configuration file
# See: https://docs.astral.sh/ruff/configuration/

# Enable auto-fixing of rule violations
fix = true

# Show source code in violation messages
show-source = true

# Show fixes in violation messages
show-fixes = true

# Respect .gitignore files
respect-gitignore = true

# Cache results for better performance
cache-dir = ".ruff_cache"
